import{R,D as f,a1 as g,U as T,a0 as S,a2 as j,u as w,a3 as b,K as P,e as r,i as p,r as h,x as V,M as k,m as _,j as x,V as D,b as E,c as C,s as z}from"./_virtual_settings-f0fd2118.js";import{c as F}from"./createRef-ad1ed90d.js";var n=globalThis&&globalThis.__decorate||function(c,e,t,s){var i=arguments.length,a=i<3?e:s===null?s=Object.getOwnPropertyDescriptor(e,t):s,d;if(typeof Reflect=="object"&&typeof Reflect.decorate=="function")a=Reflect.decorate(c,e,t,s);else for(var u=c.length-1;u>=0;u--)(d=c[u])&&(a=(i<3?d(a):i>3?d(e,t,a):d(e,t))||a);return i>3&&a&&Object.defineProperty(e,t,a),a},m;let o=m=class extends R{constructor({play:e,...t}){super(t),this.lastTime=-1,e&&this.play()}isPlaying(){return this.playing()}getCurrentTime(){return this.clampTime(this.time())}getDuration(){return this.video().duration}desiredSize(){const e=super.desiredSize();if(e.x===null&&e.y===null){const t=this.video();return{x:t.videoWidth,y:t.videoHeight}}return e}completion(){return this.clampTime(this.time())/this.video().duration}video(){const e=this.src(),t=`${this.key}/${e}`;let s=m.pool[t];return s||(s=document.createElement("video"),s.src=e,m.pool[t]=s),s.readyState<2&&f.collectPromise(new Promise(i=>{const a=()=>{i(),s.removeEventListener("canplay",a)};s.addEventListener("canplay",a)})),s}seekedVideo(){const e=this.video(),t=this.clampTime(this.time());return e.playbackRate=this.playbackRate(),e.paused||e.pause(),this.lastTime===t||this.setCurrentTime(t),e}fastSeekedVideo(){const e=this.video(),t=this.clampTime(this.time());if(e.playbackRate=this.playbackRate(),this.lastTime===t)return e;const s=this.playing()&&t<e.duration&&e.playbackRate>0;return s?e.paused&&f.collectPromise(e.play()):e.paused||e.pause(),Math.abs(e.currentTime-t)>.2?this.setCurrentTime(t):s||(e.currentTime=t),e}draw(e){this.drawShape(e);const t=this.alpha();if(t>0){const s=this.view().playbackState(),i=s===g.Playing||s===g.Presenting?this.fastSeekedVideo():this.seekedVideo(),a=T.fromSizeCentered(this.computedSize());e.save(),e.clip(this.getPath()),t<1&&(e.globalAlpha*=t),e.imageSmoothingEnabled=this.smoothing(),S(e,i,a),e.restore()}this.clip()&&e.clip(this.getPath()),this.drawChildren(e)}applyFlex(){super.applyFlex();const e=this.video();this.element.style.aspectRatio=(this.ratio()??e.videoWidth/e.videoHeight).toString()}setCurrentTime(e){const t=this.video();t.readyState<2||(t.currentTime=e,this.lastTime=e,t.seeking&&f.collectPromise(new Promise(s=>{const i=()=>{s(),t.removeEventListener("seeked",i)};t.addEventListener("seeked",i)})))}setPlaybackRate(e){let t;if(j(e)?(t=e(),w().warn({message:"Invalid value set as the playback rate",remarks:`<p>The <code>playbackRate</code> of a <code>Video</code> cannot be reactive.</p>
<p>Make sure to use a concrete value and not a function:</p>
<pre><code class="language-ts"><span class="hljs-comment">// wrong ✗</span>
video.<span class="hljs-title function_">playbackRate</span>(<span class="hljs-function">() =&gt;</span> <span class="hljs-number">7</span>);
<span class="hljs-comment">// correct ✓</span>
video.<span class="hljs-title function_">playbackRate</span>(<span class="hljs-number">7</span>);
</code></pre><p>If you&#39;re using a signal, extract its value before passing it to the property:</p>
<pre><code class="language-ts"><span class="hljs-comment">// wrong ✗</span>
video.<span class="hljs-title function_">playbackRate</span>(mySignal);
<span class="hljs-comment">// correct ✓</span>
video.<span class="hljs-title function_">playbackRate</span>(<span class="hljs-title function_">mySignal</span>());
</code></pre>`,inspect:this.key,stack:new Error().stack})):t=e,this.playbackRate.context.setter(t),this.playing())if(t===0)this.pause();else{const s=b().time,i=s(),a=this.time();this.time(()=>this.clampTime(a+(s()-i)*t))}}play(){const e=b().time,t=e(),s=this.time(),i=this.playbackRate();this.playing(!0),this.time(()=>this.clampTime(s+(e()-t)*i))}pause(){this.playing(!1),this.time.save(),this.video().pause()}seek(e){const t=this.playing();this.time(this.clampTime(e)),t?this.play():this.pause()}clampTime(e){const t=this.video().duration;return this.loop()&&(e%=t),P(0,t,e)}collectAsyncResources(){super.collectAsyncResources(),this.seekedVideo()}};o.pool={};n([r()],o.prototype,"src",void 0);n([p(1),r()],o.prototype,"alpha",void 0);n([p(!0),r()],o.prototype,"smoothing",void 0);n([p(!1),r()],o.prototype,"loop",void 0);n([p(1),r()],o.prototype,"playbackRate",void 0);n([p(0),r()],o.prototype,"time",void 0);n([p(!1),r()],o.prototype,"playing",void 0);n([h()],o.prototype,"completion",null);n([h()],o.prototype,"video",null);n([h()],o.prototype,"seekedVideo",null);n([h()],o.prototype,"fastSeekedVideo",null);o=m=n([V("Video")],o);let y;y??(y=new k("media-video",!1));y.loadData({version:0,shared:{background:"rgb(36,36,36)",range:[0,null],size:{x:1920,y:1080},audioOffset:0},preview:{fps:30,resolutionScale:1},rendering:{fps:60,resolutionScale:2,colorSpace:"srgb",fileType:"image/png",quality:1}});const L=y;let v;v??(v=new k("media-video",!1));v.loadData({version:1,timeEvents:[],seed:3374664546});const M=v,O="/examples/example-0a0a4e3f.mp4",l=_(function*(c){const e=F();c.add(x(o,{ref:e,src:O})),e().play(),yield*e().scale(1.25,2).to(1,2)});l.name="media-video";M.attach(l.meta);l.onReplaced??(l.onReplaced=new D(l.config));const $=E({scenes:[l]}),H=C("media-video",{core:"3.14.0",two:"3.14.0",ui:"3.14.0",vitePlugin:"3.14.0"},[],$,L,z);export{H as default};
