name: Deploy to GitHub Pages

on: workflow_dispatch

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: ./docs
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: ./docs/package-lock.json
      - run: npm ci
        working-directory: ./docs

      - uses: actions/checkout@v3
        with:
          repository: motion-canvas/core
          token: ${{ secrets.CORE_TOKEN }}
          path: ./core
          ref: master
      - run: npm ci
        working-directory: ./core

      - run: mkdir -p ./docs/docs/api && cp ./core/CONTRIBUTING.md ./docs/docs/api/CONTRIBUTING.md

      - name: Build website
        working-directory: ./docs
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build
